version: "3.8"

services:
  api:
    build: api
    expose:
      - 3000
    environment:
      DB_USERNAME: oldschool
      DB_PASSWORD: oldschool
      DB_DATABASE: oldschool
      DB_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PRIFIX:
      REDIS_PASSWORD:
    networks:
    - traefik-net
    - backend
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.api-oldschool.rule=Host(`api.oldschool.localhost`)"
    depends_on:
    - db
    - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: oldschool
      POSTGRES_USER: oldschool
      POSTGRES_DB: oldschool
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    networks:
      - backend
  
  redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - "redis_data:/data" # Pas besoin d'ajouter d'argument à la command
    networks:
    - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
  traefik-net:
    external: true 
